#!/bin/sh

## hyphop ##


#[ "$DEV" ] || DEV=/dev/mmcblk0

UBOOT=
DEV=

for a in "$@"; do
    case $a in
    *.bin)
    [ -f "$a" ] && {
	UBOOT=$a
    }
    ;;
    /dev/*)
    [ -b $a ] && {
	DEV=$a
    }
    ;;
    esac
done

sudo=sudo

[ "$UBOOT" ] || {
    echo "[e] undef UBOOT ">&2
    exit 1
}

[ "$DEV" ] || {
    echo "[e] undef block DEV">&2
    exit 1
}

echo "[i] wite u-boot $UBOOT to dev $DEV">&2

cat /sys/class/block/${DEV#/dev/}/device/model

CMD(){
    echo "[#] $@">&2
    "$@"
}

echo "wait 5sec">&2
sleep 1

CMD $sudo dd if=$UBOOT of=$DEV conv=fsync,notrunc bs=444 count=1
CMD $sudo dd if=$UBOOT of=$DEV conv=fsync,notrunc bs=512 skip=1 seek=1

sync




